
spring:
  application:
    name: kill-batch-system

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-drop-mysql.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  batch:
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3306/classicmodels
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: study
    password: 1234
